### PR TITLE
WIP: Edits and restructuring

### PR DESCRIPTION
**Pull request by rgieseke**
Idea for structure

- intro
- data sources
- individual gases

This is work-in-progress but feel free to comment as i go @znicholls

### CODE REVIEW

**Comment by znicholls** [comment]
Good structure. Might need one more section, 'explanation of choices/combinations' and maybe also 'updates' (which explains how we can update the emissions in future, in particular which sources are regularly updated and which are more static)

**Comment by rgieseke** [comment]
@znicholls Good points! I had thought to describe the general approach of choices in the intro and the decision in each respective section -- the updating/outlook should be done in the discussion!

**Comment by znicholls** [comment]
Re CEDS, one thing that i still don't understand is how it relates to the scenario database. Are they likely to be the same in future?

**Comment by rgieseke** [comment]
Don't know, the public release of the CEDS database has been delayed for a while: https://github.com/JGCRI/CEDS

This page has CEDS in its title, but nowhere else: https://db1.ene.iiasa.ac.at/CEDSDB/dsd?Action=htmlpage&page=about

I don't think they are related.

**Pull request merged**
