### PR TITLE
Ensure sources are downloaded in Makefile

### PR DESCRIPTION
**Pull request by rgieseke**

### CODE REVIEW

**Comment by rgieseke** [comment]
Can you try again @znicholls ?

**Comment by znicholls** [comment]
`raw-data/rcp/20THCENTURY_EMISSIONS.DAT` does not exist...

**Comment by znicholls** [comment]
I'll try again in the morning

**Comment by rgieseke** [comment]
Maybe it was a problem with the server?

**Comment by znicholls** [comment]
Nah still getting `File b'/Users/znicholls/Documents/AGCEC/Papers/global-emissions/raw-data/rcp/20THCENTURY_EMISSIONS.DAT' does not exist`

**Comment by rgieseke** [comment]
Hm, maybe one still has to run `make download` manually (i can reproduce ther problem here with a clean checkout).

Maybe not worth fixing as we might decide to include files in the repo directly if they are not doi-archived somewhere.

**Comment by rgieseke** [comment]
Thanks again! I restored the two files (html volcanic table, budget projections) as they were downloaded without scripts) -- there is some work to do to fully automate and document everything ...

**Comment by znicholls** [comment]
Ye cool sounds good. It’ll get there!

**Pull request merged**
