### PR TITLE
Tidy up

### PR DESCRIPTION
**Pull request by znicholls**
Get everything running on a fresh clone.

### CODE REVIEW

**Comment by znicholls** [comment]
@rgieseke where are the extensions meant to come from?

**Comment by rgieseke** [comment]
Thanks for looking into this!
The extension comes from here: 

https://github.com/openclimatedata/global-biomass-burning-emissions/blob/master/data/gbbe-extended.csv

https://github.com/openclimatedata/global-biomass-burning-emissions/blob/master/scripts/combine.py

It is joining the VUA 1.2 Global Biomass Burning Emissions prepared for input4MIPs together with GFED4s which has been updated until more recent years on its website.

I'm trying a fresh clone now to figure out what's missing in this repo.

**Comment by znicholls** [comment]
Ah ok I think combine is just being called too late (it needs to be called before all the plotting stuff, not after right?)

**Comment by rgieseke** [comment]
For me plots work, except for the missing "download" task.

The combine.py script i linked to is from the Biomass repo, in this repo combine.py creates the "final" output csv with all inputs.

**Comment by znicholls** [comment]
hmm have I broken something then? Do you want to open a new PR with the 'download' task added in?

**Comment by rgieseke** [comment]
I think the issue is that once a directory in "raw-data" exists, the "make download" task will not run again, so the git checkouts are not updated. Did you try a complete fresh clone? In that case this explanation wouldn't hold of course.

**Comment by znicholls** [comment]
> Did you try a complete fresh clone? In that case this explanation wouldn't hold of course.

I ran `make -B all` so that shouldn't be the reason?

**Comment by rgieseke** [comment]
> I ran make -B all so that shouldn't be the reason?

Hmm, i'll add "download" ... let's see if that helps.

**Comment by znicholls** [comment]
superceded by #27

**Pull request closed without merging**
